import subprocess
from typing import List


def get_disk_usage(parameters: List[str]): # assuming the passed parameters are already in list format

    #sample parameters generated by chatgpt.
    safe_df_parameters = [
    '-a',  # Include all filesystems
    '-h',  # Human-readable format
    '-i',  # Inode usage
    '-k',  # Display in kilobytes
    '-l',  # Local filesystems only
    '-m',  # Display in megabytes
    '-T',  # Show filesystem type
    '-x',  # Exclude filesystem types (e.g., -x tmpfs -x devtmpfs)
    '-B 1024',  # Display in 1024-byte blocks
    '-P',  # POSIX output format
    '-s',  # Sync before reading
    '--total',  # Add a total line at the end
    '--exclude-type=tmpfs',  # Exclude tmpfs filesystems
    '--exclude-type=devtmpfs'  # Exclude devtmpfs filesystems
]
    
    is_safe = set(parameters).issubset(set(safe_df_parameters))
    if is_safe:
        command = "df -h " + parameters
    else:
        command = "df -h"



    try:
        result = subprocess.run(
            command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True
        )
        usage = result.stdout.strip().decode()
    except:
        raise Exception("An unexpected error was observed")

    return usage
